{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "discord-invite-page.serviceAccountName" . }}
  labels:
{{ include "discord-invite-page.labels" . | nindent 4 }}
{{- end -}}
