{{- if .Values.prometheus.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "github-exporter.fullname" . }}
  labels:
    {{- include "github-exporter.labels" . | nindent 4 }}
{{- if .Values.prometheus.servicemonitor.labels }}
{{ toYaml .Values.prometheus.servicemonitor.labels | indent 4}}
{{- end }}
spec:
  jobLabel: {{ template "github-exporter.fullname" . }}
  selector:
    matchLabels:
      {{- include "github-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - targetPort: 9504
    path: {{ .Values.prometheus.servicemonitor.path }}
    interval: {{ .Values.prometheus.servicemonitor.interval }}
    scrapeTimeout: {{ .Values.prometheus.servicemonitor.scrapeTimeout }}
{{- end }}