apiVersion: v1
appVersion: 0.1.0
description: A Helm chart to redirect all requests to another URL
name: website-redirect
version: 0.1.0
home: https://github.com/mect/charts
maintainers:
- email: github@mect.io
  name: MECT Team
