apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expino.fullname" . }}-expino
  labels:
    {{- include "expino.labels" . | nindent 4 }}
    mect.io/component: expino
data:
data:
  variables.js: |-
    window.expino = {};
    window.expino.LOGO = {{ .Values.configuration.logoURL | quote }};
    window.expino.THEMECOLOR = {{ .Values.configuration.themeColor | quote }};
    window.expino.HOST = {{ .Values.configuration.apiURL | quote }};
    window.expino.WEATHERCITY = {{ .Values.configuration.watherCity | quote }};
