{{ $root := .}}
{{- range .Values.displays }}
---
{{- if .ingress.enabled -}}
{{- $fullName := include "expino.fullname" $root -}}
{{- $svcPort := $root.Values.service.port -}}
{{- if semverCompare ">=1.14-0" $root.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ .name }}
  labels:
    {{- include "expino.labels" $root | nindent 4 }}
    mect.io/component: expino
    mect.io/display-name: {{ .name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .ingress.tls }}
  tls:
  {{- range .ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}-{{ .name }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}