kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "expino.fullname" . }}-api
  labels:
    {{- include "expino.labels" . | nindent 4 }}
    mect.io/component: expino
spec:
  accessModes:
  {{- range .Values.api.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | quote }}
  {{- if ne .Values.api.persistence.storageClass  "-" }}
  storageClassName: {{ .Values.api.persistence.storageClass | quote }}
  {{- end }}