{{ $root := .}}
{{- range .Values.displays }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "expino.fullname" $root }}-{{ .name }}
  labels:
    {{- include "expino.labels" $root | nindent 4 }}
    mect.io/component: expino
    mect.io/display-name: {{ .name }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: {{ $root.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "expino.selectorLabels" $root | nindent 4 }}
    mect.io/component: expino
    mect.io/display-name: {{ .name }}
{{- end }}