apiVersion: v1
kind: Service
metadata:
  name: {{ include "expino.fullname" . }}-api
  labels:
    {{- include "expino.labels" . | nindent 4 }}
    mect.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "expino.selectorLabels" . | nindent 4 }}
    mect.io/component: api
