# Default values for pg-backup-s3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/mect/pg-backup-s3
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

schedule: "0 0 * * *" # https://cron.help

config: {}
  # s3Bucket: test
  # s3Region: eu-central-1
  # s3Endpoint: https://s3.eu-central-1.wasabisys.com/
  # namePrefix: pg-backup-staging
  # errorWebhook: slackWebhookURL
  # encryptionKeySecretName: secret-name
  # encryptionKeySecretKey: key
  # s3AccessKeySecretName: secret-name
  # s3AccessKeySecretKey: s3-access-key
  # s3AccessSecretSecretName: secret-name
  # s3AccessSecretSecretKey: s3-secret-key
  # postgresql: 
  #   host: pg.pg.svc.cluster.local
  #   database: postgres
  #   usernameSecretName: secret-name
  #   usernameSecretKey: username
  #   passwordSecretName: secret-name
  #   passwordSecretName: password